fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "window_minimize",
            "window_toggle_maximize",
            "window_toggle_fullscreen",
            "window_exit_fullscreen_windowed",
            "window_get_state",
            "window_close",
            "window_start_drag",
            "open_music_login",
            "clear_music_login",
            "open_update_installer",
            "restart_app",
            "configure_global_hotkeys",
            "export_json_file",
            "import_json_file",
            "set_desktop_lyrics_enabled",
            "update_desktop_lyrics",
            "get_desktop_lyrics_state",
            "update_touch_bar_lyrics",
            "set_wallpaper_mode",
            "update_wallpaper_mode",
            "set_lyrics_pointer_capture",
            "set_lyrics_hot_bounds",
            "set_lyrics_lock_state",
            "move_lyrics_by",
        ]),
    ))
    .expect("failed to build Tauri application permissions");
}
