// Transitional global bindings required by classic scripts.
// Remove each binding when its owning domain is migrated to TypeScript.
var ZERO_VEC: THREE.Vector3;
var BASE_FOV: number;
var FREE_CAMERA_MOVE: THREE.Vector3, FREE_CAMERA_TARGET_VEL: THREE.Vector3, FREE_CAMERA_SHAKE_DIR: THREE.Vector3;
var FREE_CAMERA_EULER: THREE.Euler, FREE_CAMERA_RESET_MAT: THREE.Matrix4, FREE_CAMERA_RESET_QUAT: THREE.Quaternion;
var FREE_CAMERA_UP: THREE.Vector3, CAM_PUNCH_MIN_INTERVAL: number, CAM_PUNCH_BEAT_THRESHOLD: number;
var CLICK_THRESHOLD: number, UI_HIT_SELECTOR: string, PLANE_SIZE: number;
var RIPPLE_MAX: number, GRID_X: number, GRID_Y: number;
var PCOUNT: number, LASER_BEAM_COUNT: number, LASER_SPARKS_PER_BEAM: number;
var LASER_SPARK_COUNT: number, LASER_BALL_COUNT: number, HEXAGRAM_PRESET_INDEX: number;
var PARTICLE_CLOCK_PRESET_INDEX: number, STROBE_PRESET_INDEX: number, TOPOGRAPHY_PRESET_INDEX: number, FLOAT_COUNT: number;
var SKULL_PRESET_INDEX: number, SKULL_MODEL_BASE_ROTATION_X: number, SKULL_MODEL_BASE_ROTATION_Y: number;
var SKULL_MODEL_SCALE: number, SKULL_MODEL_BASE_POSITION: Point3D, BACK_COVER_COUNT: number;
var LYRIC_CAMERA_LOCK_MAX_SCALE: number, LYRIC_SCENE_MODES: string[], CUSTOM_BG_DB_NAME: string;
var CUSTOM_BG_STORE: string, COLOR_LAB_PRESETS: ColorLabPreset[], STAGE_LYRIC_MAX_LINES: number;
var IDLE_PARTICLE_ALPHA: number;
var SEARCH_HISTORY_STORE_KEY: string, SEARCH_ORIGINAL_ARTIST_HINTS: SearchArtistHint[], USER_FX_ARCHIVE_STORE_KEY: string;
var USER_FX_ARCHIVE_EXPORT_TYPE: string, USER_FX_ARCHIVE_SCHEMA: number, LOGIN_GUIDE_SEEN_STORE_KEY: string;
var IDLE_GUIDE_BACKGROUND_ENABLED: boolean, PARTICLE_POINTER_SPIN_X: number, PARTICLE_POINTER_SPIN_Y: number;
var PARTICLE_HAND_SPIN_X: number, PARTICLE_HAND_SPIN_Y: number, PARTICLE_SPIN_MAX: number;
var HAND_SMOOTH_ALPHA: number, HAND_BONES: Array<[number, number]>, PEEK_HIDE_DELAY: number;
var SECONDARY_PLAYLIST_EDGE_MIN_X: number, SECONDARY_PLAYLIST_EDGE_MAX_X: number, SECONDARY_PLAYLIST_EDGE_DWELL_MS: number;
var SECONDARY_PLAYLIST_SEAM_CLOSE_X: number;
