declare let diyPlayerMode: boolean;
declare let startupLoginStatusPromise: Promise<unknown[]> | null;
declare let collectNameInput: HTMLInputElement | null;
declare let customLyricInput: HTMLTextAreaElement | null;

declare function applyDiyMode(enabled: boolean, options: { save: boolean }): void;
declare function bindFxPanel(): void;
declare function applySavedLyricPaletteState(): void;
declare function bindQualityControl(): void;
declare function bindPlayerControlAnimations(): void;
declare function applyUserCapsuleAutoHideState(): void;
declare function applyFxFabAutoHideState(): void;
declare function applyControlsAutoHidePreference(): void;
declare function setShelfMode(mode: string): void;
declare function applyStartupStarfieldPreset(): void;
declare function applyPlaylistPanelPinState(save: boolean): void;
declare function createBackCoverLayer(): void;
declare function initIdleGuideCanvas(): void;
declare function refreshLoginStatus(force?: boolean): Promise<LoginApiResponse | null>;
declare function refreshQQLoginStatus(): Promise<PlatformStatus>;
declare function refreshKugouLoginStatus(): Promise<PlatformStatus>;
declare function startQQLoginStatusAutoRefresh(): void;
declare function loadHomeDiscover(force: boolean): unknown;
declare function maybeRunStartupLoginGuide(reason: string): void;
declare function createPlaylistFromCollect(): void;
declare function updateCustomCoverButton(): void;

declare function __mineradioInitCoreAppState01(): void;
declare function __mineradioInitCoreAppState03(): void;
declare function __mineradioInitCoreAppState05(): void;
declare function __mineradioInitCoreAppState07(): void;
declare function __mineradioInitCoreAppState09(): void;
declare function __mineradioInitCoreAppState13(): void;
declare function __mineradioInitCoreAppState15(): void;
declare function __mineradioInitCoreAppState18(): void;
declare function __mineradioInitCoreAppState20(): void;
declare function __mineradioInitCoreAppState22(): void;
declare function __mineradioInitVisualCamera27(): void;
declare function __mineradioInitVisualParticlesBase29(): void;
declare function __mineradioInitVisualParticleSpecial30(): void;
declare function __mineradioInitVisualSkullParticles31(): void;
declare function __mineradioInitLyricsLyricEffects32(): void;
declare function __mineradioInitVisualCoverDepth34(): void;
declare function __mineradioInitAudioOfflineAnalysis35(): void;
declare function __mineradioInitLibraryShelfInteractions37(): void;
declare function __mineradioInitDiscoveryHomeData38(): void;
declare function __mineradioInitDiscoverySearch40(): void;
declare function __mineradioInitAudioPlayback41(): void;
declare function __mineradioInitLibraryPlaylistPanel42(): void;
declare function __mineradioInitVisualCoverMedia43(): void;
declare function __mineradioInitUiFxPanel44(): void;
declare function __mineradioInitUiFxArchives45(): void;
declare function __mineradioInitUiFxPanel46(): void;
declare function __mineradioInitAccountLogin47(): void;
declare function __mineradioInitUiGuides48(): void;
declare function __mineradioInitUiGesture49(): void;
declare function __mineradioInitUiChrome50(): void;
declare function __mineradioInitUiSplash51(): void;
declare function initializeDesktopIntegration(): void;
